language: python
python:
  - "3.6"
services:
  - mongodb
before_install:
  - pip install --upgrade pip
  - pip install --only-binary=numpy,scipy numpy scipy
  - pip install --upgrade pytest
install: pip install .
script: pytest
